import Head from "next/head";
import styles from "../styles/Home.module.css";

export default function About() {
  return (
    <div className={styles.landing_container}>
      <Head>
        <title>Communal Tech</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main
        className={
          "text-center px-2 md:px-14 lg:px-40 mx-4 md:mx-6 lg:mx-20 2xl:mx-40 my-4 md:my-6 lg:my-10 2xl:my-20"
        }
      >
        <div className={styles.main_margin}>
          <div
            className={
              "text-2xl md:text-3xl lg:text-4xl 2xl:text-6xl mb-1 md:mb-2"
            }
          >
            <h2 className={styles.line_height}>
              ABOUT <br /> COMMUNAL TECH
            </h2>{" "}
          </div>

          <p
            className={
              "font-robotoMono text-base md:text-sm lg:text-md xl:text-lg 2xl:text-xl mb-10"
            }
          >
            Communal Tech is a technical community management consulting company
            founded by 'Kylee Codes' in January 2022. Kylee previously worked as
            a freelance web designer, software engineer intern at Red Hat, computer science
            student, and content creator. <br />
            Kylee is mostly self-taught, has been a lifelong computer science nerd, and is finishing up her Computer Science degree, with a heavy focus on studying advanced programming languages, such as Rustlang. 
            <br /> <br />
            <a className = "font-bold" href="https://twitter.com/kyleecodes">
              Follow Kylee on Twitter!
            </a>
          </p>
          <button className={styles.primary_button}>
            <a
              target="_blank"
              href="https://blljhazo9cp.typeform.com/to/vOzyqBjF"
              rel="noopener noreferrer"
            >
              {" "}
              Let's Connect!{" "}
            </a>
          </button>
        </div>
      </main>
    </div>
  );
}
