import Head from "next/head";
import styles from "../styles/Home.module.css";
import ContactButton from "../components/ContactButton";


export default function About() {
  return (
    <div className={styles.landing_container}>
      <Head>
        <title>Communal Tech</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.float_container}>
          <div className={styles.float_left}>
            
          <div className={styles.landing_header}>
                ABOUT COMMUNAL TECH
              </div>
            <div className={styles.landing_container}>
              <div className={styles.landing_text}>
                {" "}
                Communal Tech is a technical community management consulting company founded by 'Kylee Codes' in January 2022. Kylee previously worked as a freelance web designer, software engineer, computer science student, and content creator, before entering web3 full-time in October 2021! <br />
                Kylee has been a crypto fan since 2014 and has been actively engaged in the web3 space since 2020.
                <br />
                
              </div>
              <div className={styles.landing_buttons}>
              <div className={styles.left_align_button}>
                <ContactButton />
              </div>
              </div>
            </div>
          </div>
          <div className={styles.float_right}>
          <div className={styles.land_image_container}>
          <div className={styles.round_glimmer_animation}>
            <img className={styles.about_image} src="me.jpg" />
          </div>
          </div>
          </div>
        </div>
      </main>


    </div>
  );
}
