import Head from "next/head";
import styles from "../styles/Home.module.css";
import ContactButton from "../components/ContactButton";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Communal Tech</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.float_container}>
          <div className={styles.landing_container}>
            <div className={styles.landing_header}>
              BUILDING TECHNICAL COMMUNITIES FOR EVERYONE
              <div className={styles.landing_text}>
                {" "}
                Greetings! My name is Kylee. I'm a developer advocate and
                founder of Communal Tech. I enjoy building inclusive communities
                and breaking down abstract, technical concepts into
                easy-to-understand content. <br />
                <br />
                <a href="/about">Learn More About Communal Tech</a>
              </div>
            </div>
            <div className={styles.landing_buttons}>
              <div className={styles.left_align_button}>
                <div className={styles.landing_button}>
                  <button className={styles.glimmer_animation}>
                    <a href="/services">
                      {" "}
                      View Services{" "}
                    </a>
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
